# Generated by Django 3.2.25 on 2025-06-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danzaestilo',
            old_name='imagen_url',
            new_name='video_url',
        ),
    ]
